### ISSUE TITLE
Building without AArch64 LLVM backend is not possible

### ISSUE THREAD

**Issue by epitavy** [tpde2/tpde#13]
I have my own build of LLVM, for which I enabled only my host architecture (x86).
When building TPDE with -DTPDE_A64=Off, some AArch64 specific parts are still building and cause a build error.
For instance `tpde/src/ElfMapper.cpp:227:29: error: ‘DA_GP’ was not declared in this scope`.
I believe this is declared in LLVM AArch64  headers but I don't have theme since AArch64 target is disabled on my custom build.

By the way, target specific tests are not disabled either.

**Comment by aengelke** [comment]
You could statically link TPDE-LLVM into your shared library?

**Comment by aengelke** [comment]
Broken CMake options removed in 7bd583aca5aea38bc9bd6e41cbf3e3871c3103cf.
